### ISSUE TITLE
Pokestops

### ISSUE THREAD

**Issue by peva3** [Girish-Raguvir/PokemonGo-RedStreak#2]
Hey,

Thanks for helping out so quickly with the other issue, just wanted to know if there is anyway to put in how many pokestops/items are being collected?

Just a little confused because you mentioned pokestops in the Readme, but I didn't see anything in the console.

Thanks

**Comment by girishjeyakumar** [comment]
The farming of Pokestops is currently a little unpredictable.I am assuming the backend has some other checks apart from just the closeness to a pokestop in order to collect the items.However the farming of certain pokestops does turn out successful.You should be getting a message,as shown below, on the console from the latest commit.

![selection_005](https://cloud.githubusercontent.com/assets/9464353/17042019/ee4ed264-4fc7-11e6-855c-5c6f4a1177df.png)

**Comment by girishjeyakumar** [comment]
Pokestop farming has been made more efficient and accurate in the latest commit.
